services:
  mariadb:
    image: 8ct8pus/mariadb-alpine:1.0.11
    container_name: pdo-bind-db
    ports:
      - 3306:3306
    volumes:
      # expose mariadb config to host
      - ./docker/etc/:/docker/etc/
      # save mariadb databases to named volume
      - database:/var/lib/mysql/
volumes:
  database:
